// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://celmmsdzizebswawmdee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlbG1tc2R6aXplYnN3YXdtZGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDgwNTMsImV4cCI6MjA2NzIyNDA1M30.92JMtwj-8tXbSArQecKkpyuCcTqBy6Kwn5gwgMF4MOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});